project19/urls.py
from django.contrib import admin
from django.urls import path
from cherry.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
  
    path('insert_emp/',insert_emp,name='insert_emp'),
    path('display_data/',display_data,name='display_data'), 
    path('empdept/',empdept,name='empdept'),
    path('deptemp/',deptemp,name='deptemp'),
    path('aggregate_functions/',aggregate_functions,name='aggregate_functions'),
    path('update_data/',update_data,name='update_data'),
    path('deletion_data/',deletion_data,name='deletion_data'),
]

cherry/models.py
from django.db import models

class Dept(models.Model):
    deptno=models.IntegerField(primary_key=True)
    dname=models.CharField(max_length=100)
    loc=models.CharField(max_length=100)


    def __str__(self):
        return str(self.deptno)
class Emp(models.Model):
    empno=models.IntegerField(primary_key=True)
    ename=models.CharField(max_length=100)
    job=models.CharField(max_length=100)
    hiredate=models.DateField()
    sal=models.DecimalField(max_digits=7,decimal_places=2,)  
    comm=models.DecimalField(max_digits=7,decimal_places=2,null=True,blank=True)
    mgr=models.ForeignKey('self',on_delete=models.SET_NULL,blank=True,null=True)  
    deptno=models.ForeignKey(Dept,on_delete=models.CASCADE)


    def __str__(self):
        return str(self.empno)

class Salgrade(models.Model):
    grade=models.IntegerField(primary_key=True)
    losal=models.DecimalField(max_digits=7,decimal_places=2)
    hisal=models.DecimalField(max_digits=7,decimal_places=2)

templates/DUMMY.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>DUMMY TEMPLATE</title>
    {% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <style>
        fieldset
        {
            text-align: center;
            background-color: aqua;
            color: blue;
            font-size: x-large;
            font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
            
        }
    </style>
</head>
<body>

    
<fieldset>
    <h2 class="container d-flex justify-content-center">Template</h2>
    <center class="alert alert-info">
        <header class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container d-flex justify-content-center">
                <a class="btn btn-outline-warning mx-2" href="{% url 'home' %}">HOME</a>
                <a class="btn btn-outline-warning mx-2" href="{% url 'buttons' %}">BUTTONS</a>
                <a class="btn btn-outline-warning mx-2" href="{% url 'test1' %}">TEST</a>
                <img src="{% static 'images/p1.jpg' %}" alt="">
                
            </div>
        </header>
    </center>
    
</fieldset>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    {% block body %}

    {% endblock %}
</body>
</html>

templates/buttons.html
{% extends 'home.html' %}
{% block title %}
    <title>Buttons Template</title>
    {% endblock %}



    {% block body %}
    <button type="button" class="btn btn-outline-primary">Primary</button>
    <button type="button" class="btn btn-outline-secondary">Secondary</button>
    <button type="button" class="btn btn-outline-success">Success</button>
    <button type="button" class="btn btn-outline-danger">Danger</button>
    <button type="button" class="btn btn-outline-warning">Warning</button>
    <button type="button" class="btn btn-outline-info">Info</button>
    <button type="button" class="btn btn-outline-light">Light</button>
    <button type="button" class="btn btn-outline-dark">Dark</button>
    {% endblock %}

templates/deptemp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <STYle>
       
        h3
        {

            color:red;
        }
        h2
        {
            color: lawngreen;
        }
        h1
        {
            text-align: center;
            background-color:aqua;
            color: red;
            

        }
        table
        {
            border: 3px double red;
            text-align: center;
            width: 100%;
            
            
        }
        tr,td,tbody
        {
            border: 3px dotted blue;
            padding: 5px;
            color: fuchsia;
            
            

        }
        th
        {
            border: 3px double yellowgreen;
            padding: 10px;
            color: navy;  
            font-style: italic; 
            font-size: x-large;
        }
       
    </STYle>
</head>
<body>
    <fieldset>
       <table border="3PX">
       <tr>
        <th colspan="2"><h3>DNAME</h3></th>
        <TH colspan="2"><h3>DEPTNO</h3></TH>
        <TH colspan="3"><h3>LOC</h3></TH>
       </tr>
        {% for do in LDEO %}
        <tr>
            <td colspan="2">
           <h2>{{do.dname}}</h2>
        </td>
        <td colspan="2">
           <h2>{{do.deptno}}</h2>
        </td>
        <td colspan="3">
           <h2>{{do.loc}}</h2>
        </td>
        </tr>
        <tr><th>ENAME</th>
        <TH>EMPNO</TH>
        <TH>JOB</TH>
        <TH>MGR</TH>
        <TH>SAL</TH>
        <TH>COMM</TH>
    <TH>HIREDATE</TH></tr>
        {% for eo in do.emp_set.all %}
            <tr>
        <td>{{eo.ename}}</td>
        <td>{{eo.empno}}</td>
        <td>{{eo.job }}</td>
        <td>{{eo.mgr}}</td>
        <td>{{eo.sal}}</td>
        <td>{{eo.comm}}</td>
        <td>{{eo.hiredate}}</td>
    </tr>
        {% endfor %}
        {% endfor %}
    </table>
    </fieldset>
</body>
</html>

templates/empdept.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EMPDEPT</title>
    <style>
        fieldset
        {
            
            color: blue;
        }
        h1
        {
            background-color: aqua;
            color: red;
            text-align: center;
        }
        table
        {
            border:5px double aqua;
            padding: 5px;
            width: 100%;
       

        }
        tr,td{
            border: 3px dotted blue;
            padding: 4px;
            text-align: center;
            color: blue;
            font-size: x-large;
            

        }
        th{
            color:navy;
            border: 5px dotted greenyellow;
            padding: 10px;
            text-align: center;
            
        }
    </style>
</head>
<body>
    <fieldset>
        <h1>empdept details </h1>
        <table>
            <tr>
                <th>Empno</th>
                <th>Ename</th>
                <th>Job</th>
                <th>Hire date</th>
                <th>Sal</th>
                <th>comm</th>
                <th>MGR</th>
                <th>deptno</th>
                <th>Dname</th>
                <th>Loc</th>
            </tr>
            {%  for edos in EDO %}
               
                    <tr>
                        <td>{{edos.empno}}</td>
                        <td>{{edos.ename}}</td>
                        <td>{{edos.job}}</td>
                        <td>{{edos.hiredate}}</td>
                        <td>{{edos.sal}}</td>
                        <td>{{edos.comm}}</td>
                        <td>{{edos.mgr}}</td>
                        <td>{{edos.deptno}}</td>
                        <td>{{edos.deptno.dname}}</td>
                        <td>{{edos.deptno.loc}}</td>
                    </tr>
             
            
            {% endfor %}
                </table>
            
    </fieldset>
</body>
</html>

templates/home.html
{% extends 'test1.html' %}
{% block title %}
    <title>Home Template</title>
    {% endblock %}



    {% block body %}

    {% endblock %}

templates/test1.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <style>
        h1
        {
            text-align: center;
            background-color:aqua;
            color: red;
            

        }
        table
        {
            border: 3px double red;
            text-align: center;
            width: 100%;
            
            
        }
        tr,td,tbody
        {
            border: 3px dotted  blue;
            padding: 5px;
            color: fuchsia;
            
            

        }
        th
        {
            border: 3px double yellowgreen;
            padding: 10px;
            color: navy;  
            font-style: italic; 
            font-size: x-large;
        }
       
    </style>
</head>
<body >
    <fieldset >
<h1>Dept list peoples</h1>
<table >
   
   
    <div>
        <tr>
            <th>Deptno</th>
            <th>Dname</th>
            <th>Location</th>
        </tr>
    <tbody>
    {% for dept in depts_list %}
    <tr>
        <td>{{ dept.deptno }}</td>
        <td>{{ dept.dname }}</td>
        <td>{{ dept.loc}}</td>
    </tr>
    {% endfor %}
</tbody>
</table>
</div>
<BR>
<div>
    <h1>Emp Details </h1>
    <table>
        <tr>
            <th>Empno</th>
            <th>Ename</th>
            <th>Job</th>
            <th>Hire Date</th>
            <th>Sal</th>
            <th>Comm</th>
            <th>MGR</th>
            <th>Deptno</th>
        </tr>
        {% for emp in emps %}
       
        <tr>
            <td>{{ emp.empno }}</td>
            <td>{{ emp.ename }}</td>
            <td>{{ emp.job }}</td>
            <td>{{ emp.hiredate }}</td>
            <td>{{ emp.sal }}</td>
            <td>{{ emp.comm }}</td>
            <td>{{ emp.mgr }}</td>
            <td>{{ emp.deptno }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
</fieldset>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    

</body>
</html>